scheme: http
keycloak-port: 8442
keycloak-issuer: ${scheme}://localhost:${keycloak-port}/realms/master
keycloak-client-id: spring-addons-confidential
keycloak-secret: change-me
cognito-client-id: 12olioff63qklfe9nio746es9f
cognito-issuer: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_RzhmgLwjl
cognito-secret: change-me
auth0-client-id: TyY0H7xkRMRe6lDf9F8EiNqCo8PdhICy
auth0-issuer: https://dev-ch4mpy.eu.auth0.com/
auth0-secret: change-me

gateway-uri: ${scheme}://localhost:${server.port}
greetings-api-uri: ${scheme}://localhost:7443/greetings
ui-uri: ${scheme}://localhost:4200

server:
  port: 8080
  shutdown: graceful
  ssl:
    enabled: false

spring:
  config:
    import:
    - optional:configtree:/workspace/config/
    - optional:configtree:/workspace/secret/
  lifecycle:
    timeout-per-shutdown-phase: 30s
  security:
    oauth2:
      # When configuring an OAuth2 client with login, Spring Boot standard "provider" and "registration" properties are necessary
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak-issuer}
          cognito:
            issuer-uri: ${cognito-issuer}
          auth0:
            issuer-uri: ${auth0-issuer}
        registration:
          keycloak-confidential-user:
            authorization-grant-type: authorization_code
            client-name: Keycloak
            client-id: ${keycloak-client-id}
            client-secret: ${keycloak-secret}
            provider: keycloak
            scope: openid,profile,email,offline_access,roles
          cognito-confidential-user:
            authorization-grant-type: authorization_code
            client-name: Cognito
            client-id: ${cognito-client-id}
            client-secret: ${cognito-secret}
            provider: cognito
            scope: openid,profile,email
          auth0-confidential-user:
            authorization-grant-type: authorization_code
            client-name: Auth0
            client-id: ${auth0-client-id}
            client-secret: ${auth0-secret}
            provider: auth0
            scope: openid,profile,email,offline_access
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      - SaveSession
      routes:
      # set a redirection from / to the UI
      - id: home
        uri: ${gateway-uri}
        predicates:
        - Path=/
        filters:
        - RedirectTo=301,${gateway-uri}/ui/
      # BFF access to greetings API (with TokenRelay replacing session cookies with access tokens)
      # To be used by SPAs (Angular app in our case)
      - id: greetings-api-bff
        uri: ${greetings-api-uri}
        predicates:
        - Path=/bff/greetings-api/v1/**
        filters:
        - TokenRelay=
        - StripPrefix=3
      # direct access to greetings API (without the TokenRelay => requests should be authorized with an access tokens already)
      # To be used by OAuth2 clients like Postman or mobile apps configured as OAuth2 (public) clients
      - id: greetings-api-oauth2-clients
        uri: ${greetings-api-uri}
        predicates:
        - Path=/greetings-api/v1/**
        filters:
        - StripPrefix=2
      # access to UI resources (Angular app in our case)
      - id: ui
        uri: ${ui-uri}
        predicates:
        - Path=/ui/**
      # used by the cert manager on K8s
      - id: letsencrypt
        uri: https://cert-manager-webhook
        predicates:
        - Path=/.well-known/acme-challenge/**

# spring-addons-starter-oidc specific configuration
com:
  c4-soft:
    springaddons:
      oidc:
        # OpenID Providers configuration (shared by client and resource server filter-chains)
        ops:
        - iss: ${keycloak-issuer}
          username-claim: preferred_username
          authorities:
          - path: $.realm_access.roles
          - path: $.resource_access.*.roles
        - iss: ${cognito-issuer}
          username-claim: username
          authorities:
          - path: cognito:groups
        - iss: ${auth0-issuer}
          username-claim: $['https://c4-soft.com/user']['name']
          authorities:
          - path: $['https://c4-soft.com/user']['roles']
          - path: $.permissions
        # OAuth2 client specific configuration: mostly login, logout and CSRF protection
        client:
          client-uri: ${gateway-uri}
          # For the sake of simplicity, all requests will be processed by the client filterchain
          # A resource optimisation could be excluding actuator, swagger and cert-manager endpoints to save the creation of useless sessions
          security-matchers: /**
          permit-all:
          - /login/**
          - /oauth2/**
          - /
          - /login-options
          - "/me"
          - /ui/**
          - /v3/api-docs/**
          - /actuator/health/readiness
          - /actuator/health/liveness
          - /.well-known/acme-challenge/**
          # The Angular app needs access to the CSRF cookie (to return its value as X-XSRF-TOKEN header)
          csrf: cookie-accessible-from-js
          login-path: /ui/
          post-login-redirect-path: /ui/
          post-logout-redirect-path: /ui/
          # This is an "experemiental" feature, use with caution
          back-channel-logout-enabled: true
          # Auth0 and Cognito do not follow strictly the OpenID RP-Initiated Logout spec and need specific configuration
          oauth2-logout:
            cognito-confidential-user:
              uri: https://spring-addons.auth.us-west-2.amazoncognito.com/logout
              client-id-request-param: client_id
              post-logout-uri-request-param: logout_uri
            auth0-confidential-user:
              uri: ${auth0-issuer}v2/logout
              client-id-request-param: client_id
              post-logout-uri-request-param: returnTo
          # Auth0 requires client to provide with audience in authorization-code request
          authorization-request-params:
            auth0-confidential-user:
              - name: audience
                value: demo.c4-soft.com
            
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
    
---
spring:
  config:
    activate:
      on-profile: ssl
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      - SaveSession
      - SecureHeaders
server:
  ssl:
    enabled: true

scheme: https
keycloak-port: 8443